"""Evaluation harness -- not a test, a reporting tool. Every number in docs/results.md is
produced by running this script; results.md is generated, never hand-written (P3).

    python -m mdm.evaluate --tier dev
"""

from __future__ import annotations

import argparse
import time
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path

import duckdb
import pandas as pd

from mdm.config import REPO_ROOT, VALID_TIERS
from mdm.deterministic import deterministic_match_pairs

PairKey = tuple[str, str]


@dataclass
class PairMetrics:
    true_positives: int
    false_positives: int
    false_negatives: int
    precision: float
    recall: float
    f1: float


def _pair_metrics(predicted: set[PairKey], true: set[PairKey]) -> PairMetrics:
    tp = len(predicted & true)
    fp = len(predicted - true)
    fn = len(true - predicted)
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    return PairMetrics(tp, fp, fn, precision, recall, f1)


def true_pairs_with_noise_type(ground_truth: pd.DataFrame) -> dict[PairKey, str]:
    """Every unordered true-match pair, labeled with a best-effort noise type. Most
    identities have exactly one canonical ('exact') appearance plus corrupted ones, so a
    pair is usually (canonical, corrupted) -- labeled with the corrupted side's noise type.
    Two corrupted, non-canonical appearances of the same identity (only possible when an
    identity appears in all 3 vendors) are labeled 'multiple'."""
    pair_noise_type: dict[PairKey, str] = {}
    for _identity, group in ground_truth.groupby("true_identity_id"):
        records = group[["record_key", "noise_type"]].sort_values("record_key").to_numpy()
        for i in range(len(records)):
            for j in range(i + 1, len(records)):
                key_a, noise_a = records[i]
                key_b, noise_b = records[j]
                if noise_a == "exact" and noise_b == "exact":
                    label = "exact"
                elif noise_a == "exact":
                    label = noise_b
                elif noise_b == "exact":
                    label = noise_a
                else:
                    label = "multiple"
                pair_noise_type[(key_a, key_b)] = label
    return pair_noise_type


def recall_by_noise_type(
    predicted: set[PairKey], pair_noise_type: dict[PairKey, str]
) -> dict[str, dict]:
    true_pairs = set(pair_noise_type)
    totals = Counter(pair_noise_type[p] for p in true_pairs)
    found = Counter(pair_noise_type[p] for p in (predicted & true_pairs))
    return {
        noise_type: {
            "true_pairs": totals[noise_type],
            "recovered": found.get(noise_type, 0),
            "recall": found.get(noise_type, 0) / totals[noise_type] if totals[noise_type] else 0.0,
        }
        for noise_type in sorted(totals)
    }


def run_baseline_evaluation(tier: str, db_path: Path) -> dict:
    con = duckdb.connect(str(db_path), read_only=True)
    try:
        patient_normalized = con.execute(
            "SELECT record_key, first_name, last_name, dob, ssn FROM conformance.patient_normalized"
        ).df()
        ground_truth = con.execute(
            "SELECT record_key, true_identity_id, noise_type FROM ground_truth.ground_truth"
        ).df()
    finally:
        con.close()

    started = time.monotonic()
    predicted_df = deterministic_match_pairs(patient_normalized)
    elapsed = time.monotonic() - started

    predicted_pairs: set[PairKey] = set(
        zip(predicted_df["record_key_a"], predicted_df["record_key_b"], strict=False)
    )
    pair_noise_type = true_pairs_with_noise_type(ground_truth)
    true_pairs = set(pair_noise_type)

    metrics = _pair_metrics(predicted_pairs, true_pairs)

    return {
        "tier": tier,
        "num_records": len(patient_normalized),
        "num_true_pairs": len(true_pairs),
        "num_predicted_pairs": len(predicted_pairs),
        "metrics": asdict(metrics),
        "recall_by_noise_type": recall_by_noise_type(predicted_pairs, pair_noise_type),
        "elapsed_seconds": round(elapsed, 3),
    }


def render_results_md(result: dict) -> str:
    m = result["metrics"]
    lines = [
        "# Results",
        "",
        "Generated by `python -m mdm.evaluate` -- never hand-edited (P3). Regenerate with:",
        "",
        f"    python -m mdm.evaluate --tier {result['tier']}",
        "",
        f"## Deterministic baseline ({result['tier']} tier)",
        "",
        f"- Records: {result['num_records']}",
        f"- True match pairs (ground truth): {result['num_true_pairs']}",
        f"- Predicted pairs: {result['num_predicted_pairs']}",
        f"- Runtime: {result['elapsed_seconds']}s",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Precision | {m['precision']:.4f} |",
        f"| Recall | {m['recall']:.4f} |",
        f"| F1 | {m['f1']:.4f} |",
        f"| True positives | {m['true_positives']} |",
        f"| False positives | {m['false_positives']} |",
        f"| False negatives | {m['false_negatives']} |",
        "",
        "### Recall by noise type",
        "",
        "| Noise type | True pairs | Recovered | Recall |",
        "|---|---|---|---|",
    ]
    for noise_type, stats in result["recall_by_noise_type"].items():
        lines.append(
            f"| {noise_type} | {stats['true_pairs']} | {stats['recovered']} | "
            f"{stats['recall']:.4f} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> dict:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tier", choices=VALID_TIERS, default="dev")
    parser.add_argument("--db-path", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "docs" / "results.md")
    args = parser.parse_args(argv)

    db_path = args.db_path or (REPO_ROOT / "data" / args.tier / "mdm.duckdb")
    result = run_baseline_evaluation(args.tier, db_path)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_results_md(result), encoding="utf-8")

    m = result["metrics"]
    print(
        f"tier={args.tier} precision={m['precision']:.4f} recall={m['recall']:.4f} "
        f"f1={m['f1']:.4f} -> {args.out}"
    )
    return result


if __name__ == "__main__":
    main()
