#!/usr/bin/env python
"""Estimate Fellegi-Sunter m/u parameters from labeled ground truth and write
config/fs_params.yml.

m/u are properties of the noise model, not the row count -- estimate once at dev tier,
apply unchanged at scale (PROJECT_CONSTITUTION.md #11.4).

    python scripts/estimate_fs_params.py --tier dev
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from mdm.comparators import build_nickname_index
from mdm.config import REPO_ROOT, VALID_TIERS
from mdm.evaluate import load_pair_noise_type, load_records_by_key
from mdm.fs_estimation import estimate_fs_params

DEFAULT_NICKNAME_TABLE_PATH = REPO_ROOT / "config" / "nicknames.yml"
DEFAULT_OUT_PATH = REPO_ROOT / "config" / "fs_params.yml"
DEFAULT_SAMPLE_SIZE = 20_000


def main(argv: list[str] | None = None) -> dict:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tier", choices=VALID_TIERS, default="dev")
    parser.add_argument("--db-path", type=Path, default=None)
    parser.add_argument("--sample-size", type=int, default=DEFAULT_SAMPLE_SIZE)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--nicknames", type=Path, default=DEFAULT_NICKNAME_TABLE_PATH)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT_PATH)
    args = parser.parse_args(argv)

    db_path = args.db_path or (REPO_ROOT / "data" / args.tier / "mdm.duckdb")
    records_by_key = load_records_by_key(db_path)
    true_pairs = set(load_pair_noise_type(db_path))

    with args.nicknames.open("r", encoding="utf-8") as f:
        nickname_table = yaml.safe_load(f) or {}
    nickname_index = build_nickname_index(nickname_table)

    params = estimate_fs_params(
        records_by_key,
        true_pairs,
        sample_size=args.sample_size,
        seed=args.seed,
        nickname_index=nickname_index,
    )

    header = (
        "# Generated by scripts/estimate_fs_params.py -- do not hand-edit weights.\n"
        f"# tier={args.tier} sample_size={args.sample_size} seed={args.seed}\n"
        "# m = P(agreement level | true match), u = P(agreement level | non-match),\n"
        "# weight = log2(m/u) in bits. See PROJECT_CONSTITUTION.md #11.4.\n"
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(params, f, sort_keys=False, default_flow_style=False)

    print(f"tier={args.tier} true_pairs={len(true_pairs)} -> {args.out}")
    return params


if __name__ == "__main__":
    main()
